#SPDX-License-Identifier: MIT-0
---
- name: Instalar nginx
  ansible.builtin.apt:
    name: nginx
    state: latest
    update_cache: true

- name: Crear directorio webroot
  ansible.builtin.file:
    path: "{{ directorio_web }}"
    state: directory
    mode: '0755'

- name: Copiar página estática
  ansible.builtin.template:
    src: index.html.j2
    dest: "{{ directorio_web }}/index.html"

- name: Copiar Javascript
  ansible.builtin.template:
    src: api.js.j2
    dest: "{{ directorio_web }}/api.js"

- name: Configurar reverse proxy
  ansible.builtin.template:
    src: nginx.conf.j2
    dest: "/etc/nginx/sites-available/{{ nombre_sitio }}"
    mode: '0644'

- name: Habilitar sitio {{ nombre_sitio }}
  ansible.builtin.file:
    src: "/etc/nginx/sites-available/{{ nombre_sitio }}"
    dest: "/etc/nginx/sites-enabled/{{ nombre_sitio }}"
    state: link

- name: Deshabilitar sitio default
  ansible.builtin.file:
    path: /etc/nginx/sites-enabled/default
    state: absent
  notify: reiniciar nginx
